### ISSUE TITLE
ANR getTotalListenerInfo

### ISSUE THREAD

**Issue by denisStuzo** [Kount/kount-android-sdk#29]
I see many ANRs in firebase crashlytics that point to **AnalyticsCollector.getTotalListenerInfo** function.  Could you take a look?
Here are the examples:

`main (runnable):tid=1 systid=14992 
#00 pc 0x4c0c7c libart.so (art::DumpNativeStack + 108) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#01 pc 0x4b84d8 libart.so (art::Thread::DumpStack const + 388) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#02 pc 0x4b7e18 libart.so (art::DumpCheckpoint::Run + 164) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#03 pc 0x3cd064 libart.so (art::Thread::RunCheckpointFunction + 148) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#04 pc 0x5b1130 libart.so (artTestSuspendFromCode + 232) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#05 pc 0x34a41c libart.so (art_quick_test_suspend + 156) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
       at java.lang.Class.getDeclaredField(Native method)
       at com.kount.api.analytics.AnalyticsCollector.getTotalListenerInfo(AnalyticsCollector.kt:269)
       at com.kount.api.analytics.AnalyticsCollector.addListener(AnalyticsCollector.kt:226)
       at com.kount.api.analytics.AnalyticsCollector.setUIListeners(AnalyticsCollector.kt:205)
       at com.kount.api.analytics.AnalyticsCollector.trackUIElements(AnalyticsCollector.kt:156)
       at com.kount.api.analytics.AnalyticsCollector.trackUIElements(AnalyticsCollector.kt:161)
       at com.kount.api.analytics.AnalyticsCollector.access$trackUIElements(AnalyticsCollector.kt)
       at com.kount.api.analytics.AnalyticsCollector$setUIListeners$1.onGlobalLayout(AnalyticsCollector.kt:185)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1165)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4535)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3239)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11197)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
       at android.view.Choreographer.doFrame(Choreographer.java:1055)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`
       
`main (runnable):tid=1 systid=18262 
#00 pc 0x4c0c7c libart.so (art::DumpNativeStack + 108) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#01 pc 0x4b84d8 libart.so (art::Thread::DumpStack const + 388) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#02 pc 0x4b7e18 libart.so (art::DumpCheckpoint::Run + 164) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#03 pc 0x3cd064 libart.so (art::Thread::RunCheckpointFunction + 148) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#04 pc 0x5b0f00 libart.so (artJniMethodStart + 252) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#05 pc 0x5c2378 libart.so (art_jni_method_start + 40) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
       at android.graphics.RenderNode.nCreate(Native method)
       at android.graphics.RenderNode.<init>(RenderNode.java:227)
       at android.graphics.RenderNode.create(RenderNode.java:243)
       at android.view.View.<init>(View.java:5500)
       at com.kount.api.analytics.AnalyticsCollector.getTotalListenerInfo(AnalyticsCollector.kt:269)
       at com.kount.api.analytics.AnalyticsCollector.addListener(AnalyticsCollector.kt:226)
       at com.kount.api.analytics.AnalyticsCollector.setUIListeners(AnalyticsCollector.kt:191)
       at com.kount.api.analytics.AnalyticsCollector.trackUIElements(AnalyticsCollector.kt:156)
       at com.kount.api.analytics.AnalyticsCollector.trackUIElements(AnalyticsCollector.kt:161)
       at com.kount.api.analytics.AnalyticsCollector.access$trackUIElements(AnalyticsCollector.kt)
       at com.kount.api.analytics.AnalyticsCollector$setUIListeners$1.onGlobalLayout(AnalyticsCollector.kt:185)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1142)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3644)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
       at android.view.Choreographer.doCallbacks(Choreographer.java:952)
       at android.view.Choreographer.doFrame(Choreographer.java:882)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

**Comment by gjd-keynetics** [comment]
We no longer monitor this repository. Please post your question or issue in Kount Community (https://support.kount.com/hc/en-us/community/topics) or email [support@kount.com](mailto:support@kount.com).
