### ISSUE TITLE
App crash after adding new version 3.3

### ISSUE THREAD

**Issue by waqassatti** [Kount/kount-android-sdk#7]
FATAL EXCEPTION: pool-7-thread-1
                                                                Process: com.keek.debug, PID: 32268
                                                                java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/instantapps/InstantApps;
                                                                    at com.kount.api.DataCollector$2.run(DataCollector.java:490)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.instantapps.InstantApps" on path: DexPathList[[zip file "/data/app/com.keek.debug-2/base.apk", zip file "/data/app/com.keek.debug-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.keek.debug-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.keek.debug-2/lib/arm64, /data/app/com.keek.debug-2/base.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.keek.debug-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                    at com.kount.api.DataCollector$2.run(DataCollector.java:490) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                    at java.lang.Thread.run(Thread.java:818) 
                                                                	Suppressed: java.lang.ClassNotFoundException: com.google.android.instantapps.InstantApps
                                                                    at java.lang.Class.classForName(Native Method)
                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                    		... 5 more
                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by cmavromichalis** [comment]
Hello waqassatti,

Looking into this, thanks for the report. What version Android Studio are you on?

**Comment by mwaqassatti** [comment]
I am using android studio 3.0.1

**Comment by gjd-keynetics** [comment]
This seems to be a dependency problem due to our added Instant App support.  If you are using gradle, add the following to your applications gradle dependencies for the module that uses the DataCollector and  it should add the Instant App libraries to your project:

`compile 'com.google.android.instantapps:instantapps:1.1.0'`

NOTE: You do NOT need to make your project an Instant App.  However if you decide to support instant app within your application, this dependency should auto resolve. 

We will add some documentation to this release explaining this better.

**Comment by mwaqassatti** [comment]
@gjd-keynetics  Thanks it work's now.
